"""empty message

Revision ID: 046d5043e3a8
Revises: 27b4308009bb
Create Date: 2022-10-23 18:59:22.934122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046d5043e3a8'
down_revision = '27b4308009bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_num', sa.INTEGER(), nullable=True))
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=60), nullable=True))
    op.drop_column('user', 'phone_num')
    # ### end Alembic commands ###
