"""empty message

Revision ID: 27b4308009bb
Revises: 
Create Date: 2022-10-16 17:57:11.699502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b4308009bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(length=60)))
    op.add_column('user', sa.Column('address_l1', sa.String(length=240)))
    op.add_column('user', sa.Column('address_l2', sa.String(length=240)))
    op.add_column('user', sa.Column('zip_code', sa.String(length=6)))
    op.add_column('user', sa.Column('country', sa.String(length=60)))
    op.add_column('user', sa.Column('region', sa.String(length=60)))
    op.add_column('user', sa.Column('dietary_restrictions', sa.String()))
    op.add_column('user', sa.Column('ingredients_restrictions', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ingredients_restrictions')
    op.drop_column('user', 'dietary_restrictions')
    op.drop_column('user', 'region')
    op.drop_column('user', 'country')
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'address_l2')
    op.drop_column('user', 'address_l1')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
