"""empty message

Revision ID: 3aef29e86fb4
Revises: 046d5043e3a8
Create Date: 2022-10-24 21:27:43.284101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aef29e86fb4'
down_revision = '046d5043e3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('name', sa.String(length=100)))
    op.add_column('post', sa.Column('description', sa.Text()))
    op.add_column('post', sa.Column('ingredients', sa.Text()))
    op.add_column('post', sa.Column('serving_size', sa.Text()))
    op.add_column('post', sa.Column('servings', sa.Text()))
    op.add_column('post', sa.Column('ingredients_raw_str', sa.Text()))
    op.add_column('post', sa.Column('steps', sa.Text()))
    op.add_column('post', sa.Column('key_words', sa.Text()))
    op.add_column('post', sa.Column('meals', sa.Text()))
    op.add_column('post', sa.Column('prepare_time', sa.Text()))
    op.add_column('post', sa.Column('food_types', sa.Text()))
    op.add_column('post', sa.Column('user', sa.Text()))
    op.add_column('post', sa.Column('ingredients_choice', sa.Text()))
    op.drop_column('post', 'title')
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.TEXT(), nullable=False))
    op.add_column('post', sa.Column('title', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('post', 'ingredients_choice')
    op.drop_column('post', 'user')
    op.drop_column('post', 'food_types')
    op.drop_column('post', 'prepare_time')
    op.drop_column('post', 'meals')
    op.drop_column('post', 'key_words')
    op.drop_column('post', 'steps')
    op.drop_column('post', 'ingredients_raw_str')
    op.drop_column('post', 'servings')
    op.drop_column('post', 'serving_size')
    op.drop_column('post', 'ingredients')
    op.drop_column('post', 'description')
    op.drop_column('post', 'name')
    # ### end Alembic commands ###
