"""empty message

Revision ID: eb74fbb9ac71
Revises: 3aef29e86fb4
Create Date: 2022-10-24 22:20:02.894737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb74fbb9ac71'
down_revision = '3aef29e86fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from pathlib import Path
    file_name = Path(__file__).parents[1].joinpath('clean_data.csv')
    op.execute(f"COPY Post FROM '{file_name}' WITH CSV;", execution_options=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'ingredients_choice', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('post', 'user', existing_type=sa.TEXT(),nullable=True)
    op.alter_column('post', 'food_types', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('post', 'prepare_time', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('post', 'meals', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('post', 'key_words', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('post', 'steps', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('post', 'ingredients_raw_str', existing_type=sa.TEXT(),nullable=True)
    op.alter_column('post', 'servings', existing_type=sa.TEXT(),nullable=True)
    op.alter_column('post', 'serving_size', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('post', 'ingredients',existing_type=sa.TEXT(), nullable=True)
    op.alter_column('post', 'description', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('post', 'name', existing_type=sa.VARCHAR(length=100), nullable=True)

    # ### end Alembic commands ###
