credentials:
  usernames:
    dheeraj:
      email: dheeraj.kumar@morganstanley.com
      name: Dheeraj
      password: '$2b$12$CpPkzBFr7Z7JpSzx44Za5OqTMQJ8CQVehWrNxrROhhkn/7VIBS8y.' # To be replaced with hashed password
    dheeraj1:
      email: dheeraj1.kumar1@morganstanley.com
      name: Dk
      password: '$2b$12$PjdIPnfhkw4FtwjW6pPwG.g3wpcEsZiaBK4a4uZ.OC0Jc6rl28aYy' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: food_4_all_key
  name: food_4_all_cookie
preauthorized:
  emails:
  - dheeruymv@gmail.com